### ISSUE TITLE
Configured Favicon isn't used

### ISSUE THREAD

**Issue by USSX-Hares** [jenkinsci/simple-theme-plugin#130]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.387.1
OS: Linux - 5.15.0-56-generic
Java: 11.0.13 - Ubuntu (OpenJDK 64-Bit Server VM)
---
Parameterized-Remote-Trigger:3.1.6.3
StashBranchParameter:0.3.0
active-directory:2.30
analysis-model-api:11.0.0
ant:481.v7b_09e538fcca
antisamy-markup-formatter:159.v25b_c67cd35fb_
apache-httpcomponents-client-4-api:4.5.14-150.v7a_b_9d17134a_5
artifactory:3.18.0
atlassian-bitbucket-server-integration:3.3.2
authentication-tokens:1.4
bitbucket:223.vd12f2bca5430
bitbucket-build-status-notifier:1.4.2
bitbucket-pullrequest-builder:1.5.0
bootstrap4-api:4.6.0-5
bootstrap5-api:5.2.2-1
bouncycastle-api:2.27
branch-api:2.1071.v1a_188a_562481
build-keeper-plugin:19.va_df8a_2c65123
build-name-setter:2.2.0
build-timeout:1.28
build-user-vars-plugin:1.9
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:2.0.0
cloudbees-bitbucket-branch-source:796.v6cb_1559e1673
cloudbees-folder:6.815.v0dd5a_cb_40e0e
cobertura:1.17
code-coverage-api:4.0.0
command-launcher:90.v669d7ccb_7c31
commons-lang3-api:3.12.0-36.vd97de6465d5b_
commons-text-api:1.10.0-36.vc008c8fcda_7b_
conditional-buildstep:1.4.2
config-file-provider:3.11.1
copyartifact:686.v6fd37018d7c2
credentials:1224.vc23ca_a_9a_2cb_0
credentials-binding:523.vd859a_4b_122e6
custom-tools-plugin:0.8
cvs:2.19.1
dashboard-view:2.472.v9ff2a_e6a_c529
data-tables-api:1.13.3-2
delivery-pipeline-plugin:1.4.2
display-url-api:2.3.7
docker-commons:419.v8e3cd84ef49c
downstream-build-cache:1.7
durable-task:504.vb10d1ae5ba2f
echarts-api:5.4.0-2
email-ext:2.95
envinject:2.901.v0038b_6471582
envinject-api:1.199.v3ce31253ed13
extended-choice-parameter:359.v35dcfdd0c20d
extended-read-permission:3.2
external-monitor-job:203.v683c09d993b_9
extra-tool-installers:1.2
font-awesome-api:6.3.0-1
forensics-api:2.0.1
generic-webhook-trigger:1.86.2
gerrit-trigger:2.39.0
gerrit-verify-status-reporter:0.0.3
git:5.0.0
git-client:4.2.0
git-parameter:0.9.18
git-server:99.va_0826a_b_cdfa_d
github:1.37.0
github-api:1.303-417.ve35d9dd78549
github-branch-source:1701.v00cc8184df93
global-build-stats:244.v27c8a_2e50a_34
gradle:2.3.2
groovy-label-assignment:1.2.0
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
hidden-parameter:70.va_40299ce5d83
html-audio-notifier:0.4
html5-notifier-plugin:1.5
htmlpublisher:1.31
implied-labels:0.11
instance-identity:142.v04572ca_5b_265
ionicons-api:45.vf54fca_5d2154
ivy:2.4
jackson2-api:2.14.2-319.v37853346a_229
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javadoc:226.v71211feb_e7e9
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.8-1
jdk-tool:63.v62d2fd4b_4793
jenkins-jira-issue-updater:1.18
jersey2-api:2.38-1
jira:3.9
jira-trigger:1.0.2
jjwt-api:0.11.5-77.v646c772fddb_0
jquery:1.12.4-1
jquery3-api:3.6.3-1
jsch:0.1.55.61.va_e9ee26616e7
junit:1189.v1b_e593637fa_e
ldap:671.v2a_9192a_7419d
lenientshutdown:1.1.1
locale:226.v008e1b_58cb_b_0
lockable-resources:1131.vb_7c3d377e723
log-parser:2.3.0
mailer:448.v5b_97805e3767
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.1.6
matrix-combinations-parameter:1.3.2
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.21
mercurial:1260.vdfb_723cdcc81
metrics:4.2.13-420.vea_2f17932dd6
mina-sshd-api-common:2.9.2-50.va_0e1f42659a_a
mina-sshd-api-core:2.9.2-50.va_0e1f42659a_a
msbuild:1.30
multiple-scms:0.8
naginator:1.18.2
nant:248.vcc8a_3eec8db_a
node-iterator-api:49.v58a_8b_35f8363
nvm-wrapper:0.1.7
okhttp-api:4.10.0-132.v7a_7b_91cef39c
pam-auth:1.10
parameterized-scheduler:1.2
parameterized-trigger:2.45
pipeline-build-step:487.va_823138eee8b_
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-groovy-lib:629.vb_5627b_ee2104
pipeline-input-step:466.v6d0a_5df34f81
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2118.v31fd5b_9944b_5
pipeline-model-definition:2.2118.v31fd5b_9944b_5
pipeline-model-extensions:2.2118.v31fd5b_9944b_5
pipeline-rest-api:2.31
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2118.v31fd5b_9944b_5
pipeline-stage-view:2.31
pipeline-utility-steps:2.15.1
plain-credentials:143.v1b_df8b_d3b_e48
platformlabeler:1834.v30a_0cdf167e7
plugin-util-api:3.1.0
popper-api:1.16.1-3
popper2-api:2.11.6-2
postbuild-task:1.9
postbuildscript:3.2.0-460.va_fda_0fa_26720
powershell:2.0
preSCMbuildstep:44.v6ef4fd97f56e
prism-api:1.29.0-3
prometheus:2.1.1
publish-over:0.22
publish-over-ssh:1.24
pyenv-pipeline:2.1.2
python:1.3
rebuild:1.34
repo:1.16.0
resource-disposer:0.21
role-strategy:587.v2872c41fa_e51
run-condition:1.5
saferestart:0.7
scm-api:631.v9143df5b_e4a_a
scp:1.8
script-security:1229.v4880b_b_e905a_6
shelve-project-plugin:3.2
simple-theme-plugin:146.v0e67db_a_9052e
snakeyaml-api:1.33-95.va_b_a_e3e47b_fa_4
sounds:0.7
ssh:2.6.1
ssh-agent:327.v230ecd01f86f
ssh-credentials:305.v8f4381501156
ssh-slaves:2.877.v365f5eb_a_b_eec
sshd:3.275.v9e17c10f2571
stashNotifier:1.28
structs:324.va_f5d6774f3a_d
subversion:2.17.1
timestamper:1.22
token-macro:321.vd7cc1f2a_52c8
trilead-api:2.84.v72119de229b_7
variant:59.vf075fe829ccb
versioncolumn:95.v82f3985cd6e1
vsphere-cloud:2.27
warnings-ng:10.0.2
workflow-aggregator:596.v8c21c963d92d
workflow-api:1208.v0cc7c6e0da_9e
workflow-basic-steps:1010.vf7a_b_98e847c1
workflow-cps:3641.vf58904a_b_b_5d8
workflow-durable-task-step:1234.v019404b_3832a
workflow-job:1284.v2fe8ed4573d4
workflow-multibranch:733.v109046189126
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:839.v35e2736cfd5c
ws-cleanup:0.44
xshell:129.v99c1dcfa_d3d2
yet-another-build-visualizer:1.16
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

I upgraded Jenkins and all plugins to the latest version. After that, it stops appearing.

I tried:
 * Place favicon file to `/userContent` directory and change URL to `/userContent/favicon.svg`
 * Use both favicon URLs at the same time
 * Restart Jenkins multiple times

Favicon I used: https://dwglogo.com/wp-content/uploads/2017/11/Jenkins-logo-003.svg
Theme: 
![image](https://user-images.githubusercontent.com/29100587/226101487-6f6f78b9-dac9-4956-b088-d2d43addb883.png)

### Expected Results

The chosen favicon is used.

### Actual Results

![image](https://user-images.githubusercontent.com/29100587/226101496-6fc3a039-9a1d-4066-a48d-eec9cd3d7523.png)

Only default favicon is requested by the site. No topic-related errors nor warnings are shown in the browser console, no failed media requests.

### Anything else?

Only happened after upgrade. Can't tell if it is because of plugin or Jenkins update.
Furthermore, if I request `/userContent/favicon.svg` manually, the SVG can be requested, is truely identical to the SVG from the Web, but can't be displayed.

![image](https://user-images.githubusercontent.com/29100587/226101652-9ba88ae8-28da-4071-bb26-8d0d54ac5666.png)

**Comment by piyush5566** [comment]
Hi, I am also facing this issue.
But this issue is not coming with Firefox.

**Comment by TobiX** [comment]
I cannot reproduce this in any browser I have at hand. Which browser (& version) are you using? On which OS? The favicon replacement is kinda hacky, so I'm not surprised it might break in some browsers...

**Comment by USSX-Hares** [comment]
I'm using Chrome on Windows. The tricky part is the fact it worked in the very same browser session before I updated Jenkins and pluggins. Since I upgraded them simultaneously, i can't tell which one caused that behaviour.23:40, 19 марта 2023 г., Tobias Gruetzmacher ***@***.***>:
I cannot reproduce this in any browser I have at hand. Which browser (& version) are you using? On which OS? The favicon replacement is kinda hacky, so I'm not surprised it might break in some browsers...

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by piyush5566** [comment]
Hi, Please find the OS and browser details below:

OS - Windows 11 Pro 21H2
Chrome version - 111.0.5563.65(64-bit)
--> Issue is coming
Firefox version - 102.9.0esr(32-bit)
--> Issue not coming

One of my colleagues reported that this issue is also coming with Chrome and Safari on MacOs

**Comment by altaroinj** [comment]
The same occured for me after Jenkins was updated to 2.387.1 LTS version.
The issue occurs on Edge and Chrome, but not on Firefox.
Did anyone find a solution ?

**Comment by USSX-Hares** [comment]
@altaroinj agreed, works in firefox, not works in Chrome

![image](https://user-images.githubusercontent.com/29100587/234830224-a41af789-b930-4ed4-9b60-7ae3f7de9f9d.png)

**Comment by ala-ableton** [comment]
For reference, this issue is due to changes in Jenkins from the following PR:
- https://github.com/jenkinsci/jenkins/pull/6768

**Comment by lemeurherve** [comment]
cc @NotMyFault FYI (not checked)

**Comment by NotMyFault** [comment]
> cc NotMyFault FYI (not checked)

What am I supposed to look for 👀 

If plugins want to overwrite non-API items, they are on their own. I recommend, maintainers introduce a favicon API in core, similar to buttons, colors, styling, etc., downstream can consume and adjust to their needs (e.g., the dark theme plugin).
Randomly overwriting data outside an API scope is expected to change at any time without notice.

**Comment by TobiX** [comment]
@NotMyFault ACK. This was a hack in the first place and I'm not surprised it broke. I won't bother to introduce an API for this in core, since it's trivially possible to replace the favicon via other means (For example, you could just replace the favicon using the reverse proxy in front of the Jenkins controller)

If I'll come around to it, I'll see if I can fix the hack now that I know what to look for.
