### ISSUE TITLE
Not visible in system configuration 

### ISSUE THREAD

**Issue by shyam-30** [jenkinsci/simple-theme-plugin#204]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  i installed simple theme but is is not visible in system configuration .
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

i am using jenkins master . i installed simple theme then refresh jenkins but still theme is not visible in system configuration 

### Reproduction steps

1. go to available plugins
2. search simple theme
3. select simple theme and install 
4. go to system configuration 
5. restart jenkins 
6. search theme 
7. not visible here 

### Expected Results

theme should be show in system configuration 

### Actual Results

not available

**Comment by TobiX** [comment]
Since the end of last year (https://github.com/jenkinsci/jenkins/pull/8403), all "appearance" plugins have a dedicated category in the system configuration, the settings of this plugin should appear there. Please reopen this issue if you cannot find it there.
