### ISSUE TITLE
User-defined themes no longer work in Jenkins 2.346.1

### ISSUE THREAD

**Issue by pcarenza** [jenkinsci/simple-theme-plugin#83]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Windows Server 2019

### Reproduction steps

- Write CSS using material theme website, download css file, place in web-accessible location. In my case I had an embedded SVG and light blue color
- point theme at CSS and refresh
- Title shows correctly, but none of the colors are correct and icon doesn't show up
- This worked in Jenkins 2.332.X

### Expected Results

Theme properly displays with blue and icon

### Actual Results

Theme is entirely black, no icon

**Comment by breakingspell** [comment]
It seems some CSS has changed with 2.346.1. We use a small Extra CSS entry to theme the headers on the two Jenkins instances we use to tell them apart by glance. 
After adjusting the CSS to match the new version, the header is fixed, but the breadcrumb bar colors are not correct:
`
.page-header, .jenkins-breadcrumbs
{
background-color:darkred;
}
`
The breadcrumb bar takes on a barely-pink tint, same with our other instance's `green` being a very light green, almost white. It's enough to tell them apart as intended, but not the previous behavior in 2.332.x (breadcrumb bar fully matching header and much easier to see). 

I have't had a chance to drill further, I suspect `background-color` is no longer the right property to set for the breadcrumb bar. Many people may need to update their themes for this release

**Comment by TobiX** [comment]
This is not an issue in this plugin, but with the individual theme(s) instead (Hint: The material theme is dead "upstream", you might want to switch and help improve the [material-theme-plugin](https://github.com/jenkinsci/material-theme-plugin/) instead). Jenkins Core has started some more breaking UI improvements in recent months, so breaking themes are almost guaranteed.
